// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1edm7gbiSHXOqF7XjLekaC6pUwHX15jA',
    appId: '1:933035228249:android:74498a41fea64434ca4548',
    messagingSenderId: '933035228249',
    projectId: 'baby-control-tracker',
    storageBucket: 'baby-control-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz1z5THXte9dfXNT_het9bc0SjrM3pymg',
    appId: '1:933035228249:ios:4b504de2ec672340ca4548',
    messagingSenderId: '933035228249',
    projectId: 'baby-control-tracker',
    storageBucket: 'baby-control-tracker.firebasestorage.app',
    iosClientId: '933035228249-qukbu1rdjqpankt4r3ecvf17lsrcmqbh.apps.googleusercontent.com',
    iosBundleId: 'com.controlbebe.controlBebe',
  );
}
