// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// IMPORTANTE: Ejecuta `dart pub global activate flutterfire_cli` y luego
// `flutterfire configure` para reemplazar este archivo con tu configuración real.
//
// Mientras tanto, usa estos valores placeholder para que la app arranque.
// Obtén los valores reales en Firebase Console > Configuración del proyecto > Tus apps.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlaS6r6HbsqYk6fNgWzno5d0V025jG0fY',
    appId: '1:933035228249:web:4131ff00331dd8b6ca4548',
    messagingSenderId: '933035228249',
    projectId: 'baby-control-tracker',
    authDomain: 'baby-control-tracker.firebaseapp.com',
    storageBucket: 'baby-control-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1edm7gbiSHXOqF7XjLekaC6pUwHX15jA',
    appId: '1:933035228249:android:74498a41fea64434ca4548',
    messagingSenderId: '933035228249',
    projectId: 'baby-control-tracker',
    storageBucket: 'baby-control-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz1z5THXte9dfXNT_het9bc0SjrM3pymg',
    appId: '1:933035228249:ios:4b504de2ec672340ca4548',
    messagingSenderId: '933035228249',
    projectId: 'baby-control-tracker',
    storageBucket: 'baby-control-tracker.firebasestorage.app',
    iosClientId: '933035228249-qukbu1rdjqpankt4r3ecvf17lsrcmqbh.apps.googleusercontent.com',
    iosBundleId: 'com.controlbebe.controlBebe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_IOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.controlBebe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_WEB_API_KEY',
    appId: 'REPLACE_WITH_YOUR_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    authDomain: 'REPLACE_WITH_YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'REPLACE_WITH_YOUR_PROJECT_ID.appspot.com',
  );
}